name: Release Binary

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Install Wix
      uses: actions/checkout@v2
      with:
        repository: fbarresi/wix
        path: wix

    - name: Download go-msi
      run: go get github.com/mh-cbon/go-msi

    - name: Create template dir and download templates
      run: | 
        mkdir $GOROOT/templates
        pwd
        curl https://raw.githubusercontent.com/mh-cbon/go-msi/master/templates/LicenseAgreementDlg_HK.wxs -o $GOROOT/templates
        curl https://raw.githubusercontent.com/mh-cbon/go-msi/master/templates/WixUI_HK.wxs -o $GOROOT/WixUI_HK.wxs
        curl https://raw.githubusercontent.com/mh-cbon/go-msi/master/templates/product.wxs -o $GOROOT/product.wxs

    - name: Make WIX Templates
      run: go-msi generate-templates --out build-templates --version 1.0.2

    - name: Build MSI Package
      run: go-msi make --msi svccheck.msi --src build-templates --version 1.0.2

    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@latest
      with:
        # GitHub secret token
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: Latest Build
        files: | 
          *.exe