name: Release Binary

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Install Wix
      uses: actions/checkout@v2
      with:
        repository: fbarresi/wix
        path: wix

    - name: Download go-msi
      run: go get github.com/mh-cbon/go-msi

    - name: Create template dir and download templates
      run: | 
        mkdir "templates"
        curl https://raw.githubusercontent.com/mh-cbon/go-msi/master/templates/LicenseAgreementDlg_HK.wxs -o ".\templates\LicenseAgreementDlg_HK.wxs"
        curl https://raw.githubusercontent.com/mh-cbon/go-msi/master/templates/WixUI_HK.wxs -o ".\templates\WixUI_HK.wxs"
        curl https://raw.githubusercontent.com/mh-cbon/go-msi/master/templates/product.wxs -o ".\templates\product.wxs"

    - name: Generate RTF format license
      run: go-msi to-rtf --src LICENSE --out LICENSE.rtf --reencode

    - name: Make WIX Templates
      run: go-msi generate-templates --src ".\templates" --out . --version 1.0.2

    - name: Build Setup
      run: |
        wix\tools\candle.exe LicenseAgreementDlg_HK.wxs WixUI_HK.wxs product.wxs
        wix\tools\light.exe -ext WixUIExtension -ext WixUtilExtension -sacl -spdb -out svccheck.msi LicenseAgreementDlg_HK.wixobj WixUI_HK.wixobj product.wixobj

    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@latest
      with:
        # GitHub secret token
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: Latest Build
        files: | 
          *.exe